language: bash

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx

script:
    - bash equality_test.sh
    
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d5946ed953960c36b414
    on_success: change
    on_failure: always
    on_start: never 
